name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: kauannsantos
          outputs: dist/github-snake-dark.svg?palette=github-dark

      - name: Colorir a cobra
        run: |
          sed -i 's/stroke:#79b8ff/stroke:#C0344D/g' dist/github-snake-dark.svg
          sed -i 's/fill:#79b8ff/fill:#C0344D/g' dist/github-snake-dark.svg
          sed -i 's/#79b8ff/#C0344D/g' dist/github-snake-dark.svg

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
